"use client";
import { useState } from "react";
import { Plus, Save, Trash2 } from "lucide-react";
import { adminFetch } from "@/lib/adminFetch";
import type { FaqData } from "@/lib/faqs";

const BLANK = { question: "", answer: "", category: "General", categoryDescription: "", linkLabel: "", linkHref: "", displayOrder: 0, status: "published" as const };
const field = "mt-1 w-full rounded-xl border border-rule bg-white px-3 py-2 text-sm text-ink outline-none focus:border-accent";
const label = "text-[10px] font-bold uppercase tracking-[.08em] text-ink-faint";

export function FaqManager({ initial }: { initial: FaqData[] }) {
  const [items, setItems] = useState(initial); const [draft, setDraft] = useState(BLANK); const [saving, setSaving] = useState(""); const [message, setMessage] = useState("");
  function patch(id: string, update: Partial<FaqData>) { setItems((current) => current.map((item) => item._id === id ? { ...item, ...update } : item)); }
  async function create() { setMessage(""); const response = await adminFetch("/api/admin/faqs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); const data = await response.json().catch(() => ({})); if (!response.ok) return setMessage(data.error || "Could not add FAQ"); setItems((current) => [...current, data.faq]); setDraft(BLANK); setMessage("FAQ added."); }
  async function save(item: FaqData) { setSaving(item._id); const response = await adminFetch(`/api/admin/faqs/${item._id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(item) }); const data = await response.json().catch(() => ({})); setSaving(""); setMessage(response.ok ? "FAQ saved." : data.error || "Could not save FAQ"); }
  async function remove(item: FaqData) { if (!window.confirm(`Delete “${item.question}”?`)) return; const response = await adminFetch(`/api/admin/faqs/${item._id}`, { method: "DELETE" }); if (!response.ok) return setMessage("Could not delete FAQ"); setItems((current) => current.filter((faq) => faq._id !== item._id)); }
  const editor = (value: typeof BLANK | FaqData, set: (key: string, value: string | number) => void) => <div className="grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2"><span className={label}>Question *</span><input className={field} value={value.question} onChange={(e) => set("question", e.target.value)} /></label><label className="sm:col-span-2"><span className={label}>Answer *</span><textarea rows={3} className={`${field} resize-y`} value={value.answer} onChange={(e) => set("answer", e.target.value)} /></label><label><span className={label}>Category *</span><input className={field} value={value.category} onChange={(e) => set("category", e.target.value)} /></label><label><span className={label}>Category subtitle</span><input className={field} value={value.categoryDescription} onChange={(e) => set("categoryDescription", e.target.value)} /></label><label><span className={label}>Optional link label</span><input className={field} value={value.linkLabel} onChange={(e) => set("linkLabel", e.target.value)} /></label><label><span className={label}>Optional link destination</span><input className={field} value={value.linkHref} onChange={(e) => set("linkHref", e.target.value)} placeholder="/licence" /></label><label><span className={label}>Display order</span><input type="number" min="0" className={field} value={value.displayOrder} onChange={(e) => set("displayOrder", Number(e.target.value))} /></label><label><span className={label}>Visibility</span><select className={field} value={value.status} onChange={(e) => set("status", e.target.value)}><option value="published">Published</option><option value="hidden">Hidden</option></select></label></div>;
  return <div className="space-y-5">{message && <p className="rounded-xl bg-accent-wash px-4 py-3 text-sm text-ink">{message}</p>}<section className="card p-4 sm:p-6"><div className="mb-4 flex items-center justify-between"><div><p className="label-muted">New entry</p><h2 className="mt-1 font-display text-xl font-bold text-ink">Add an FAQ</h2></div><Plus size={20} className="text-accent" /></div>{editor(draft, (key, value) => setDraft((current) => ({ ...current, [key]: value })))}<button type="button" onClick={create} className="btn-primary mt-4"><Plus size={15} /> Add FAQ</button></section><div className="space-y-3">{items.map((item) => <article key={item._id} className="card p-4 sm:p-5">{editor(item, (key, value) => patch(item._id, { [key]: value }))}<div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => remove(item)} className="btn-danger gap-2 px-4"><Trash2 size={14} /> Delete</button><button type="button" onClick={() => save(item)} disabled={saving === item._id} className="btn-primary gap-2 px-4"><Save size={14} /> {saving === item._id ? "Saving…" : "Save"}</button></div></article>)}</div></div>;
}
