import mongoose, { Schema, models, model } from "mongoose";

/**
 * License — the entitlement. This is the single source of truth for
 * "is this person allowed to download this file right now".
 *
 * One licence per (order, product) pair, enforced by a compound unique
 * index. That index is load-bearing: it is what makes the payment
 * webhook safe to run twice. Razorpay fires both `payment.captured` and
 * `order.paid` for the same payment, so the delivery path WILL be
 * re-entered — the second attempt hits a duplicate-key error on this
 * index and is caught and ignored, rather than minting a second key and
 * sending a second delivery email.
 *
 * Never check entitlement against Order.paymentStatus. Check it here.
 * A refund flips status to "revoked" and the order row is irrelevant.
 */

export interface ILicense {
  _id: string;
  key: string;
  order: mongoose.Types.ObjectId;
  user: mongoose.Types.ObjectId;
  product: mongoose.Types.ObjectId;

  status: "active" | "revoked";
  downloadCount: number;
  downloadLimit: number;
  lastDownloadedAt?: Date;

  githubInvited: boolean;
  githubUsername?: string;
  githubInvitedAt?: Date;

  revokedAt?: Date;
  revokedReason?: string;
  revokedBy?: mongoose.Types.ObjectId;

  createdAt: Date;
  updatedAt: Date;
}

const LicenseSchema = new Schema<ILicense>(
  {
    /** Format TB-XXXX-XXXX-XXXX. Generated by lib/licenseKey.ts. */
    key: {
      type: String,
      required: true,
      unique: true,
      uppercase: true,
      trim: true,
    },
    order: {
      type: Schema.Types.ObjectId,
      ref: "Order",
      required: true,
      index: true,
    },
    user: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    product: {
      type: Schema.Types.ObjectId,
      ref: "Product",
      required: true,
      index: true,
    },

    status: {
      type: String,
      enum: ["active", "revoked"],
      default: "active",
      index: true,
    },
    downloadCount: { type: Number, default: 0 },
    /** Raiseable per-licence by an admin when a customer has a genuine problem. */
    downloadLimit: { type: Number, default: 5 },
    lastDownloadedAt: { type: Date },

    githubInvited: { type: Boolean, default: false },
    githubUsername: { type: String, trim: true },
    githubInvitedAt: { type: Date },

    revokedAt: { type: Date },
    revokedReason: { type: String },
    revokedBy: { type: Schema.Types.ObjectId, ref: "User" },
  },
  { timestamps: true }
);

/** Idempotency guard for the delivery webhook. See the note above — do not drop this. */
LicenseSchema.index({ order: 1, product: 1 }, { unique: true });
LicenseSchema.index({ user: 1, createdAt: -1 });

/** True only when the licence itself permits another download right now. */
LicenseSchema.methods.canDownload = function (this: ILicense) {
  return this.status === "active" && this.downloadCount < this.downloadLimit;
};

export default models.License || model<ILicense>("License", LicenseSchema);
